# Dockerfile  
FROM debian:8

ENV DEBIAN_FRONTEND noninteractive  
RUN apt-get update && apt-get install -y unzip sudo libgtk2.0-0 libgconf2-4 libnss3 \  
            libasound2 libxtst6 libcanberra-gtk-module libgl1-mesa-glx git libnotify4 libxss1
ADD ./code.deb /vcs/

WORKDIR /vcs  
RUN dpkg -i code.deb && apt-get install -f && rm code.deb  
RUN adduser --disabled-login --uid 1000 \--gecos 'dummy' dummy

CMD ["sudo","-u","dummy","/usr/bin/editor", "-w"] 

